name: Continuous Integration
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  automation-test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: npm install and test
        run: |
          npm install --legacy-peer-deeps
          npm run ci:test